
version: "3"
services:
  web:
    image: orga:latest
    ports:
      - "5000:5000"
    env_file:
      - "config/docker.dev.env"
    depends_on:
      - db
  db:
    image: postgres:9
    ports:
      - "5432:5432"
