
version: "3"
services:
  web:
    image: phx_template:latest
    ports:
      - "5000:5000"
    env_file:
      - "provision.local.env"
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - "5432:5432"
